Fabric core exception: DG.foo.evaluate(): (unknown):1:30: index (1) out of range (1)
